/**
 * Textos de UI centralizados (español). Único lugar donde viven los strings
 * visibles, compartido por web y móvil — preparado para i18n futuro (pt/en).
 */
export const es = {
  app: {
    nombre: "DIPREM CRM",
    lema: "Gestión comercial DIPREM",
  },
  auth: {
    titulo: "Iniciar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    entrar: "Entrar",
    entrando: "Entrando…",
    salir: "Cerrar sesión",
    errores: {
      emailRequerido: "Ingresa tu correo",
      emailInvalido: "Correo inválido",
      passwordCorta: "La contraseña debe tener al menos 6 caracteres",
      credenciales: "Correo o contraseña incorrectos",
      generico: "No se pudo iniciar sesión. Intenta de nuevo.",
    },
  },
  nav: {
    miDia: "Mi Día",
    cuentas: "Cuentas",
    oportunidades: "Oportunidades",
    actividades: "Actividades",
    propuestas: "Propuestas",
    reportes: "Reportes",
    admin: "Administración",
    perfil: "Perfil",
  },
  roles: {
    ejecutivo: "Ejecutivo Comercial",
    gerente: "Gerente Comercial",
    admin: "Administrador",
    lectura: "Solo lectura",
  },
  comunes: {
    cargando: "Cargando…",
    proximamente: "Disponible en una próxima fase",
    sinAcceso: "No tienes acceso a esta sección",
    guardar: "Guardar",
    guardando: "Guardando…",
    cancelar: "Cancelar",
    crear: "Crear",
    editar: "Editar",
    eliminar: "Eliminar",
    buscar: "Buscar…",
    sinResultados: "Sin resultados",
    errorGenerico: "Ocurrió un error. Intenta de nuevo.",
    confirmarEliminar: "¿Seguro que quieres eliminar este registro?",
    opcional: "opcional",
    todos: "Todos",
  },
  crm: {
    nuevaCuenta: "Nueva cuenta",
    editarCuenta: "Editar cuenta",
    razonSocial: "Razón social",
    taxId: "RUT / CUIT / Tax ID",
    vertical: "Vertical",
    pais: "País",
    ciudad: "Ciudad",
    sitioWeb: "Sitio web",
    estado: "Estado",
    propietario: "Ejecutivo",
    sinCuentas: "Aún no tienes cuentas. Crea la primera o convierte un lead.",
    contactos: "Contactos",
    nuevoContacto: "Nuevo contacto",
    editarContacto: "Editar contacto",
    nombre: "Nombre",
    cargo: "Cargo",
    telefono: "Teléfono",
    correo: "Correo",
    canalPreferido: "Canal preferido",
    contactoPrincipal: "Contacto principal",
    sinContactos: "Sin contactos registrados",
    leads: "Leads",
    nuevoLead: "Nuevo lead",
    editarLead: "Editar lead",
    empresa: "Empresa",
    fuente: "Fuente",
    calificacion: "Calificación",
    notas: "Notas",
    convertir: "Convertir",
    convertirLead: "Convertir lead en cuenta + oportunidad",
    convertido: "Convertido",
    descartarLead: "Descartar",
    sinLeads: "Sin leads por gestionar",
    oportunidades: "Oportunidades",
    nuevaOportunidad: "Nueva oportunidad",
    editarOportunidad: "Editar oportunidad",
    nombreOportunidad: "Nombre de la oportunidad",
    cuenta: "Cuenta",
    monto: "Monto",
    moneda: "Moneda",
    modalidad: "Modalidad de contrato",
    pilar: "Pilar",
    lineaServicio: "Línea de servicio",
    servicio: "Servicio",
    fechaCierre: "Cierre estimado",
    probabilidad: "Probabilidad",
    etapa: "Etapa",
    moverA: "Mover a…",
    motivoPerdida: "Motivo de pérdida",
    detalleMotivoPerdida: "Detalle (opcional)",
    registrarPerdida: "Registrar pérdida",
    sinOportunidades: "Sin oportunidades en esta etapa",
    totalPipeline: "Total",
    adjudicada: "Adjudicada 🎉",
    embudo: "Embudo de ventas",
  },
  admin: {
    etapasEmbudo: "Etapas del embudo",
    etapasDescripcion:
      "Define las etapas del proceso comercial DIPREM. El orden controla el Kanban; la probabilidad se asigna automáticamente a las oportunidades que entran a la etapa.",
    nuevaEtapa: "Nueva etapa",
    nombreEtapa: "Nombre de la etapa",
    orden: "Orden",
    probabilidadDefault: "Probabilidad %",
    esGanada: "Etapa ganada (adjudicado)",
    esPerdida: "Etapa perdida",
    activa: "Activa",
    subir: "Subir",
    bajar: "Bajar",
  },
  fase0: {
    bienvenida: "Bienvenido/a",
    descripcionMiDia:
      "Aquí verás tu agenda del día, seguimientos pendientes y avance de metas (Fase 2).",
    descripcionCuentas: "Gestión de cuentas y contactos (Fase 1).",
    descripcionOportunidades: "Embudo de ventas DIPREM en Kanban (Fase 1).",
    descripcionActividades: "Registro de llamadas, reuniones y visitas a terreno (Fase 2).",
    descripcionPropuestas: "Propuestas con versiones y aprobación gerencial (Fase 4).",
    descripcionReportes: "KPIs y reportes exportables (Fase 3).",
    descripcionAdmin: "Embudo, servicios, usuarios, equipos y metas (por fases).",
  },
} as const;

export type Strings = typeof es;
