/**
 * Textos de UI centralizados (español). Único lugar donde viven los strings
 * visibles, compartido por web y móvil — preparado para i18n futuro (pt/en).
 */
export const es = {
  app: {
    nombre: "DIPREM CRM",
    lema: "Gestión comercial DIPREM",
  },
  auth: {
    titulo: "Iniciar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    entrar: "Entrar",
    entrando: "Entrando…",
    salir: "Cerrar sesión",
    errores: {
      emailRequerido: "Ingresa tu correo",
      emailInvalido: "Correo inválido",
      passwordCorta: "La contraseña debe tener al menos 6 caracteres",
      credenciales: "Correo o contraseña incorrectos",
      generico: "No se pudo iniciar sesión. Intenta de nuevo.",
    },
  },
  nav: {
    control: "Control",
    reporteDiario: "Reporte diario",
    miDia: "Mi Día",
    cuentas: "Empresas",
    oportunidades: "Oportunidades",
    actividades: "Actividades",
    mercado: "Mercado",
    reportes: "Reportes",
    admin: "Administración",
    perfil: "Perfil",
  },
  roles: {
    ejecutivo: "Ejecutivo Comercial",
    gerente: "Gerente Comercial",
    admin: "Administrador",
    revisor: "Revisión",
    lectura: "Solo lectura",
  },
  shell: {
    mas: "Más",
    menuCompleto: "Todo el menú",
    colapsar: "Colapsar menú",
    expandir: "Expandir menú",
    modoOscuro: "Modo oscuro",
    modoClaro: "Modo claro",
    accionesRapidas: "Acciones rápidas",
    accionGestion: "Registrar gestión",
    accionLead: "Nuevo prospecto",
    accionOportunidad: "Nueva oportunidad",
  },
  buscador: {
    placeholder: "Buscar empresa, prospecto, proyecto u oportunidad…",
    abrir: "Buscar",
    escribeParaBuscar: "Escribe al menos 2 letras para buscar en todo el CRM",
    sinResultados: (texto: string) => `Sin resultados para "${texto}"`,
    grupos: {
      cuenta: "Empresas",
      lead: "Prospectos",
      oportunidad: "Oportunidades",
      proyecto: "Proyectos del mercado",
      ejecutivo: "Ejecutivos",
    },
  },
  comunes: {
    cargando: "Cargando…",
    reintentar: "Reintentar",
    cerrar: "Cerrar",
    volver: "Volver",
    proximamente: "Disponible en una próxima fase",
    sinAcceso: "No tienes acceso a esta sección",
    guardar: "Guardar",
    guardando: "Guardando…",
    cancelar: "Cancelar",
    crear: "Crear",
    editar: "Editar",
    eliminar: "Eliminar",
    buscar: "Buscar…",
    sinResultados: "Sin resultados",
    errorGenerico: "Algo falló. Intenta de nuevo.",
    confirmarEliminar: "¿Seguro que quieres eliminar este registro?",
    opcional: "opcional",
    todos: "Todos",
  },
  // Confirmación visible de cada acción (toast global)
  confirmaciones: {
    guardado: "Guardado ✓",
    gestionRegistrada: "Gestión registrada ✓",
    completada: "Actividad completada ✓",
    notaAgregada: "Nota agregada ✓",
    convertido: "Prospecto convertido en empresa + oportunidad ✓",
    etapaMovida: "Oportunidad movida de etapa ✓",
    descartado: "Prospecto descartado ✓",
    eliminado: "Eliminado ✓",
  },
  // Filtro por perfil de contacto (bucket de cargo) — Empresas y, en Fase B,
  // el detalle de proyecto del Mercado (mismo componente reutilizable)
  filtroCargo: {
    titulo: "Contactos clave",
    todos: "Todos",
    decisor_tecnico: "✅ Decisor técnico",
    gestor_compra: "🛒 Gestor de compra",
    puerta_entrada: "🚪 Puerta de entrada",
    nota: "Muestra las empresas que ya tienen identificado ese perfil de contacto",
    sinContactosClave: "Sin contactos clave",
  },
  // Errores técnicos traducidos a español claro (ver lib/errores.ts)
  errores: {
    sinPermiso: "No tienes permiso para hacer esto. Si crees que deberías poder, habla con el administrador.",
    duplicado: "Ya existe un registro con esos mismos datos.",
    sinConexion: "Sin conexión. Revisa tu internet e intenta de nuevo.",
    sesionExpirada: "Tu sesión expiró. Vuelve a iniciar sesión.",
  },
  crm: {
    nuevaCuenta: "Nueva empresa",
    editarCuenta: "Editar empresa",
    razonSocial: "Razón social",
    taxId: "RUT / CUIT / Tax ID",
    vertical: "Rubro",
    pais: "País",
    ciudad: "Ciudad",
    sitioWeb: "Sitio web",
    estado: "Estado",
    propietario: "Ejecutivo",
    sinCuentas: "Aún no tienes empresas. Crea la primera o convierte un prospecto.",
    contactos: "Contactos",
    nuevoContacto: "Nuevo contacto",
    editarContacto: "Editar contacto",
    nombre: "Nombre",
    cargo: "Cargo",
    telefono: "Teléfono",
    correo: "Correo",
    canalPreferido: "Canal preferido",
    contactoPrincipal: "Contacto principal",
    sinContactos: "Sin contactos registrados",
    buscarContactoPlaceholder: "Buscar por nombre o cargo…",
    verRestantesContactos: (n: number) => `Ver los ${n} restantes ▾`,
    verMenosContactos: "Ver menos ▴",
    linkedin: "LinkedIn",
    mejorHorario: "Mejor horario para contactar",
    mejorHorarioPlaceholder: "Ej: martes a jueves, 9:00–11:00",
    notasPrivadas: "Notas privadas",
    notasPrivadasAyuda: "Internas DIPREM: no salen en la ficha PDF.",
    fichaContacto: "Ficha de contacto",
    verFicha: "Ver ficha",
    // Perímetro 0015: PII solo por revelación (con registro y cuota diaria)
    mostrar: "Mostrar",
    masAcciones: "Más acciones",
    mostrarDatosContacto: "Mostrar datos de contacto",
    datosProtegidos: "Datos protegidos",
    revelacionRegistrada: "La revelación queda registrada (Ley 21.719)",
    limiteRevelaciones: (omitidos: number, limite: number) =>
      `Límite diario de revelaciones alcanzado (${limite}): ${omitidos} contacto(s) quedan ocultos hasta mañana.`,
    optOutAviso:
      "Esta persona se opuso al tratamiento de sus datos (Ley 21.719): no debe ser contactada.",
    exportarPdf: "Ficha en PDF",
    historialContacto: "Historial con este contacto",
    historialContactoNota:
      "Todas las interacciones con esta persona, sin importar el proyecto u oportunidad",
    leads: "Prospectos",
    nuevoLead: "Nuevo prospecto",
    editarLead: "Editar prospecto",
    empresa: "Empresa",
    fuente: "Fuente",
    calificacion: "Calificación",
    notas: "Notas",
    convertir: "Convertir",
    convertirLead: "Convertir prospecto en empresa + oportunidad",
    convertido: "Convertido",
    descartarLead: "Descartar",
    sinLeads: "Sin prospectos por gestionar",
    oportunidades: "Oportunidades",
    nuevaOportunidad: "Nueva oportunidad",
    editarOportunidad: "Editar oportunidad",
    nombreOportunidad: "Nombre de la oportunidad",
    cuenta: "Empresa",
    monto: "Monto",
    moneda: "Moneda",
    modalidad: "Modalidad de contrato",
    pilar: "Pilar",
    lineaServicio: "Línea de servicio",
    servicio: "Servicio",
    fechaCierre: "Cierre estimado",
    probabilidad: "Probabilidad",
    etapa: "Etapa",
    moverA: "Mover a…",
    motivoPerdida: "Motivo de pérdida",
    detalleMotivoPerdida: "Detalle (opcional)",
    registrarPerdida: "Registrar pérdida",
    sinOportunidades: "Sin oportunidades en esta etapa",
    totalPipeline: "Total",
    adjudicada: "Adjudicada 🎉",
    embudo: "Embudo de ventas",
    // Rediseño del embudo: una acción principal por tarjeta + dinero en juego
    avanzarA: (etapa: string) => `Avanzar → ${etapa}`,
    adjudicar: "✅ Adjudicar",
    dineroEnJuego: "💰 Dinero en juego",
    abiertasN: (n: number) =>
      n === 1 ? "1 oportunidad abierta" : `${n} oportunidades abiertas`,
    adjudicadoMes: "Adjudicado este mes",
    adjudicadasN: (n: number) => (n === 1 ? "1 adjudicada" : `${n} adjudicadas`),
    perdidasMesN: (n: number) => (n === 1 ? "1 perdida este mes" : `${n} perdidas este mes`),
    masDetalles: "＋ Agregar pilar, servicio y fecha (opcional)",
    menosDetalles: "− Ocultar detalles opcionales",
  },
  control: {
    titulo: "Panel de Control",
    descripcion:
      "Resultado, no actividad: cobertura de cartera, decisores conseguidos, embudo en movimiento y dónde intervenir hoy.",
    // Acaparador: arriba y en rojo, imposible de ignorar
    acaparadorTitulo: "Empresas reclamadas sin gestión",
    acaparadorNota: (umbral: number) =>
      `Reclamadas hace más de ${umbral} días sin ninguna gestión — cartera acaparada, no trabajada`,
    acaparadorVacio: "Ninguna empresa reclamada supera el umbral. 🎉",
    umbralDias: "Umbral",
    liberarAlPool: "Liberar al pool",
    liberando: "Liberando…",
    liberada: "Empresa devuelta al pool ✓",
    confirmarLiberar: (empresa: string) =>
      `¿Devolver "${empresa}" al pool? El ejecutivo la perderá de su cartera.`,
    // Lista agrupada por ejecutivo (la pregunta es "quién acapara")
    acaparadasDe: (n: number) =>
      n === 1 ? "1 empresa acaparada" : `${n} empresas acaparadas`,
    verMasAcaparadas: (n: number) => `Ver ${n} más ▾`,
    verMenosAcaparadas: "Ver menos ▴",
    seleccionarEmpresa: "Seleccionar para liberar",
    liberarSeleccionadas: (n: number) =>
      n === 1 ? "Liberar 1 seleccionada" : `Liberar ${n} seleccionadas`,
    confirmarLiberarVarias: (n: number, ejecutivo: string) =>
      `¿Devolver ${n === 1 ? "1 empresa" : `${n} empresas`} de ${ejecutivo} al pool? Las perderá de su cartera.`,
    liberadasN: (n: number) =>
      n === 1 ? "1 empresa devuelta al pool ✓" : `${n} empresas devueltas al pool ✓`,
    nProyectosCorto: (n: number) => (n === 1 ? "1 proyecto" : `${n} proyectos`),
    capexMaxCorto: (v: string) => `máx ${v} MUSD`,
    // Cuadro por ejecutivo — RESULTADO (el peor de cobertura arriba)
    resultadoTitulo: "Resultado por ejecutivo (30 días)",
    resultadoNota:
      "Ordenado por cobertura: el que menos cartera trabaja, primero. Las actividades no rankean.",
    colCobertura: "Cobertura 30d",
    colCarteraCorta: "Cartera",
    colDecisores: "Decisores conseguidos",
    colEmbudo: "Embudo movido",
    colHuerfanas: "Huérfanas",
    colTasaRespuesta: "Tasa respuesta",
    sinDatoTasa: "s/registro",
    verDetalle: "Ver detalle",
    // Drill-down por ejecutivo
    detalleDe: (nombre: string) => `Detalle de ${nombre}`,
    detalleCartera: (n: number, pct: string) => `Cartera: ${n} empresas · cobertura ${pct}`,
    detalleSinCriticas: "Sin empresas críticas sobre el umbral.",
    detalleSinHuerfanas: "Sin oportunidades huérfanas. ✓",
    huerfanasTitulo: "Oportunidades huérfanas",
    huerfanasNota:
      "Abiertas SIN próximo paso con fecha: eso es abandono, no gestión",
    // Reporte diario del dueño (móvil primero, legible sin zoom)
    diarioTitulo: "Reporte diario",
    diarioAbrir: "📱 Reporte diario",
    diarioSubtitulo: "Las últimas 48 horas de gestión, para leer desde el celular",
    diarioResumen: "El día en una línea",
    diarioGestiones: (n: number) => (n === 1 ? "1 gestión" : `${n} gestiones`),
    diarioConRespuesta: (n: number) => `${n} con respuesta`,
    diarioDecisores: (n: number) =>
      n === 1 ? "1 decisor conseguido" : `${n} decisores conseguidos`,
    diarioEmbudo: (n: number) => (n === 1 ? "1 avance de embudo" : `${n} avances de embudo`),
    diarioPorEjecutivo: "Por ejecutivo",
    diarioSinGestiones: "Sin gestiones en las últimas 48 horas.",
    diarioDecisoresTitulo: "🎯 Decisores conseguidos",
    diarioEmbudoTitulo: "📈 Embudo en movimiento",
    diarioAlertas: "🔴 Requiere tu intervención",
    diarioAcaparadas: (n: number, umbral: number) =>
      `${n} empresa(s) reclamadas con más de ${umbral} días sin gestión`,
    diarioHuerfanas: (n: number) => `${n} oportunidad(es) sin próximo paso con fecha`,
    diarioSinAlertas: "Sin alertas hoy. 🎉",
    diarioVolverControl: "← Panel de Control",
    avancesTitulo: "Decisores conseguidos (30 días)",
    avancesNota:
      "Empresas que pasaron de solo-puerta a decisor técnico identificado — la métrica que importa",
    sinAvances: "Nadie ha conseguido un decisor nuevo en 30 días.",
    embudoTitulo: "Movimiento de embudo (30 días)",
    retroceso: "retroceso",
    metricaProyectos: "Proyectos asignados",
    metricaProyectosNota: (trabajados: number) =>
      `${trabajados} trabajados esta semana`,
    metricaMejor: "Mejor gestión del mes",
    metricaMejorNota: (gestiones: number) =>
      gestiones === 1 ? "1 gestión registrada" : `${gestiones} gestiones registradas`,
    sinGestionesMes: "Sin gestiones aún este mes",
    metricaRiesgo: "Oportunidades en riesgo",
    metricaRiesgoNota: (dias: number) => `Más de ${dias} días sin actividad`,
    metricaPipeline: "Dinero en juego",
    metricaPipelineNota: "Suma de las oportunidades abiertas",
    semaforoTitulo: "Semáforo de ejecutivos",
    semaforoNota: "Actividad de los últimos 7 días y cumplimiento de metas del mes",
    colGestion7d: "Gestión (7 días)",
    colCumplimiento: "Cumplimiento",
    sinGestionTitulo: "Proyectos sin gestión",
    sinGestionNota: (dias: number) =>
      `Asignados sin ninguna actividad en los últimos ${dias} días`,
    todosGestionados: "Todos los proyectos asignados tienen gestión reciente. 🎉",
    recordar: "Recordar",
    recordando: "Enviando…",
    recordatorioEnviado: "Recordatorio enviado ✓",
    vencido: "Vencido",
    fechaLimiteCorta: "Límite",
    notaDelDueno: "Nota de quien asignó",
    historialTitulo: "Historial de asignaciones",
    historialNota: "Quién asignó qué proyecto, a quién y cuándo",
    colProyecto: "Proyecto",
    colAsignadoA: "Asignado a",
    colAsignadoPor: "Asignado por",
    colFecha: "Fecha",
    colEstado: "Estado",
    sinAsignaciones: "Aún no hay proyectos asignados.",
    verLead: "Ver prospecto",
  },
  notificaciones: {
    titulo: "Recordatorios",
    marcarLeida: "Marcar como vista",
    sinPendientes: "Sin recordatorios pendientes",
    campana: "Notificaciones",
    sinNotificaciones: "Estás al día. Sin notificaciones pendientes. 🎉",
    marcarTodas: "Marcar todas como vistas",
    abrir: "Abrir",
  },
  notas: {
    titulo: "Notas internas",
    descripcion:
      "Visibles solo para el ejecutivo del registro, su gerente y el administrador. Al comentar, el ejecutivo recibe una notificación.",
    placeholder: "Escribe una nota para el equipo…",
    agregar: "Agregar nota",
    agregando: "Guardando…",
    sinNotas: "Aún no hay notas internas.",
    eliminar: "Eliminar nota",
    notasDeOportunidad: (nombre: string) => `Notas internas — ${nombre}`,
  },
  mercado: {
    titulo: "Radar de Proyectos",
    descripcion:
      "La cartera de proyectos del mercado, priorizada por score. Asigna a tus ejecutivos lo que hay que trabajar ahora.",
    // Segmentos del Radar (aprobados)
    segmentos: {
      pipeline: "🔥 Ventana caliente",
      prospeccion: "🔎 Prospección",
      activo_p2: "🌿 Activo P2 (SEIA)",
      om_hse: "♻️ O&M / HSE",
      watchlist: "👁 En vigilancia",
      por_clasificar: "⏳ Por clasificar",
      descarte: "🗑 Descarte",
    },
    segmentosNota: {
      pipeline: "Ventana caliente con empresa y contacto: listos para trabajar",
      prospeccion:
        "Ventana caliente SIN contacto: urgente conseguir a la persona, el score no castiga",
      activo_p2: "Estudios (perfil→factibilidad): compran SEIA y permisos ahora",
      om_hse: "Operando: asesoría ambiental mensual y SSO recurrente",
      watchlist: "Exploración / rechazado: vigilado, reversible (editar etapa lo reactiva)",
      por_clasificar: "Sin etapa en la fuente — clasificar a mano (rediseñado = prioridad alta)",
      descarte: "Desistidos y suspendidos",
    },
    score: "Score",
    porQuePuntuo: "Por qué puntuó así",
    factorEtapa: "Etapa",
    factorCapex: "CAPEX",
    factorSector: "Sector",
    factorContactabilidad: "Contactabilidad",
    factorHistorial: "Cliente histórico",
    pilarPrimario: "Pilar primario",
    pilaresSecundarios: "También aplica",
    etapaEditable: "Etapa (editable)",
    etapaSinClasificar: "— por clasificar —",
    etapaActualizada: "Etapa actualizada (score recalculado)",
    capexCorto: "CAPEX (MUSD)",
    construccionCorta: "Constr.",
    pemCorta: "PEM",
    ultimaGestion: "Última gestión",
    sinGestionNunca: "sin gestión",
    diasCorto: (d: number) => `${d} d`,
    contactosCuenta: "Contactos",
    contactosEstado: {
      decisor: "✅ Decisor",
      gestor: "🛒 Gestor compra",
      puerta: "🚪 Solo puerta",
      ninguno: "⚠️ Sin contactos",
    },
    pedirDerivacion: "Pedir derivación",
    derivacionTitulo: "Pedir derivación al decisor técnico",
    derivacionNota:
      "La empresa tiene puerta de entrada pero ningún decisor técnico identificado. Llama al mejor contacto puerta y pide que te derive al gerente de proyecto / operaciones:",
    derivacionSinPuerta:
      "Sin contactos puerta en la empresa: consigue el primer contacto por prospección directa.",
    filtroEjecutivo: "Ejecutivo",
    sinAsignarFiltro: "Sin asignar",
    recalcular: "Recalcular scores",
    recalculado: (n: number) => `${n} proyectos recalculados`,
    importar: "Importar proyectos",
    importarTitulo: "Importar proyectos del mercado",
    seleccionarArchivo: "Selecciona un archivo Excel (.xlsx) o CSV",
    formatoAyuda:
      "Columnas esperadas: nombre del proyecto, empresa, rubro, región, monto estimado, contacto, teléfono, correo, fuente. La primera fila debe traer los encabezados.",
    analizando: "Analizando archivo…",
    previewTitulo: "Revisión antes de importar",
    filasValidas: (n: number) => (n === 1 ? "1 proyecto listo para cargar" : `${n} proyectos listos para cargar`),
    filasConError: (n: number) => (n === 1 ? "1 fila con errores (no se importará)" : `${n} filas con errores (no se importarán)`),
    duplicadosArchivo: (n: number) => `${n} duplicados dentro del archivo (se cargan una sola vez)`,
    confirmarImportar: "Importar",
    importando: "Importando…",
    resultadoImportacion: (insertados: number, duplicados: number) =>
      `Se importaron ${insertados} proyectos. ${duplicados > 0 ? `${duplicados} ya existían y no se duplicaron.` : ""}`,
    sinProyectos: "Aún no hay proyectos importados. Sube tu primer archivo del mercado.",
    proyecto: "Proyecto",
    empresa: "Empresa",
    rubro: "Rubro",
    region: "Región",
    montoEstimado: "Monto estimado",
    contacto: "Contacto",
    fuente: "Fuente",
    estado: "Estado",
    asignadoA: "Asignado a",
    estados: {
      sin_asignar: "Sin asignar",
      asignado: "Asignado",
      convertido: "Convertido",
    },
    asignar: "Asignar",
    asignarSeleccionados: (n: number) => (n === 1 ? "Asignar 1 proyecto" : `Asignar ${n} proyectos`),
    asignarTitulo: "Asignar proyectos a un ejecutivo",
    asignarDescripcion:
      "Cada proyecto se convierte en un prospecto nuevo del ejecutivo, con el teléfono y correo del contacto ya cargados. Lo verá destacado en su Mi Día.",
    ejecutivo: "Ejecutivo",
    prioridad: "Prioridad",
    fechaLimite: "Fecha límite de primer contacto",
    notaPrivada: "Nota para el ejecutivo",
    notaPrivadaAyuda:
      "Privada: solo la ven el ejecutivo asignado, su gerente y el administrador.",
    notaPlaceholder: "Ej: Este contacto conoce a Pedro, di que vas de parte de él",
    diasAlerta: "Alertarme si no hay gestión en (días)",
    asignando: "Asignando…",
    resultadoAsignacion: (asignados: number, omitidos: number) =>
      `${asignados} ${asignados === 1 ? "proyecto asignado" : "proyectos asignados"}.${omitidos > 0 ? ` ${omitidos} ya estaban asignados y se omitieron.` : ""}`,
    seleccionados: (n: number) => `${n} seleccionados`,
    // Ficha del proyecto (Fase B): ecosistema mandante + EPC + contratistas
    volverRadar: "← Radar de Proyectos",
    proyectoNoEncontrado: "Proyecto no encontrado (o sin permiso para verlo)",
    verFichaProyecto: "Ver ficha del proyecto",
    ecosistemaTitulo: "Ecosistema del proyecto",
    ecosistemaNota:
      "Mandante, EPC y contratistas que participan, con sus contactos clave",
    rolesVinculo: {
      mandante: "Mandante",
      epc: "EPC",
      contratista: "Contratista",
      proveedor: "Proveedor",
    },
    fuenteVinculo: {
      derivado: "derivado de la carga",
      manual: "vinculado a mano",
      sugerido_ia: "sugerido por IA",
    },
    vincularTitulo: "Vincular empresa al proyecto",
    vincularNota:
      "¿Qué EPC ganó el contrato? ¿Qué contratistas están en obra? Ese conocimiento hoy no se guarda en ninguna parte — quédalo aquí.",
    buscarEmpresaPlaceholder: "Busca por razón social (mínimo 2 letras)…",
    vincular: "Vincular",
    vinculada: "Empresa vinculada al proyecto ✓",
    quitarVinculo: "Quitar",
    vinculoQuitado: "Vínculo eliminado ✓",
    confirmarQuitarVinculo: (empresa: string) =>
      `¿Quitar "${empresa}" del proyecto?`,
    sinVinculadas:
      "Aún no hay EPC ni contratistas vinculados. Usa el buscador de arriba para agregar el primero.",
    contactosClaveTitulo: "Contactos clave del ecosistema",
    contactosClaveNota:
      "Nombre y cargo, sin teléfonos ni correos: la PII sigue saliendo solo por revelación con cuota",
    sinContactosEco: "Las empresas de este proyecto aún no tienen contactos registrados.",
    contactoPrincipalMarca: "★ principal",
  },
  gestion: {
    titulo: "Análisis de gestión",
    ultimaGestion: "Última gestión",
    diasSinGestion: (dias: number) =>
      dias === 0 ? "gestionado hoy" : dias === 1 ? "1 día sin gestión" : `${dias} días sin gestión`,
    sinGestiones: "Aún no hay gestiones registradas para este contacto.",
    resumenTipos: "Gestiones realizadas",
    proximaAccion: "Próxima acción",
    sinProximaAccion: "Sin próxima acción definida — agenda la siguiente gestión.",
    intensidad: "Intensidad de gestión",
    lineaTiempo: "Historial de gestiones",
    verMas: "Ver más",
    llamar: "Llamar",
    whatsapp: "WhatsApp",
    escribirCorreo: "Escribir correo",
  },
  miDia: {
    // Qué hacer hoy: la lista única ordenada por urgencia (Fase D)
    queHacerHoy: "Qué hacer hoy",
    queHacerHoyNota: "Tus próximas acciones en orden de urgencia. Parte por la primera.",
    sinAccionesHoy: "Nada urgente pendiente. Suma gestión con el registro rápido. 🎉",
    razonLimiteVencido: "Fecha límite de primer contacto vencida",
    razonPrimerContacto: "Esperando tu primer contacto",
    razonTareaVencida: "Quedó pendiente de días anteriores",
    razonAgendada: (hora: string | null) =>
      hora ? `Agendada hoy a las ${hora}` : "Agendada para hoy",
    razonSinContacto: (dias: number) =>
      dias === 1
        ? "1 día sin contacto — que no se enfríe"
        : `${dias} días sin contacto — que no se enfríe`,
    agendaHoy: "Agenda de hoy",
    vencidas: "Vencidas",
    sinAgenda: "Nada agendado para hoy. Usa el registro rápido para sumar gestión.",
    seguimientos: "Seguimientos pendientes",
    sinSeguimientos: "Sin oportunidades abiertas que requieran seguimiento. 👌",
    verEmbudo: "Ver todas las oportunidades →",
    diasSinContacto: (dias: number) =>
      dias === 0 ? "contactada hoy" : dias === 1 ? "1 día sin contacto" : `${dias} días sin contacto`,
    registrarGestion: "Registrar gestión",
    registroRapido: "Registro rápido",
    resumenDia: "Resumen del día",
    completadasHoy: "completadas hoy",
    pendientesHoy: "pendientes",
    alertasSeguimiento: "con alerta",
    completar: "Completar",
    completada: "Hecha ✓",
    yaRealizada: "Ya realizada (registrar como hecha)",
    hoy: "Hoy",
    manana: "Mañana",
    leadsNuevos: "Prospectos nuevos asignados",
    leadsNuevosNota: "Proyectos del mercado y prospectos que esperan tu primer contacto",
    verLead: "Ver prospecto",
    prioritarios: "Proyectos prioritarios de hoy",
    prioritariosNota: "Por dónde empezar: prioridad del dueño, fecha límite y urgencia",
    racha: (dias: number) =>
      dias === 1 ? "1 día seguido con gestión" : `${dias} días seguidos con gestión`,
    sinRacha: "Registra una gestión hoy para partir tu racha",
    gestionesSemana: "Gestión de la semana",
    gestionesSemanaDe: (hechas: number, meta: number) => `${hechas} de ${meta}`,
    gestionesSemanaSinMeta: (hechas: number) =>
      hechas === 1 ? "1 gestión esta semana" : `${hechas} gestiones esta semana`,
    metaSemanalNota: "Meta semanal derivada de tu meta mensual de actividades",
    resumenFinDia: "Resumen del día",
    resumenFinDiaNota: "Lo que se hizo hoy y por dónde partir mañana",
    hicisteHoy: (n: number) => (n === 1 ? "Registraste 1 gestión hoy" : `Registraste ${n} gestiones hoy`),
    quedaronPendientes: (n: number) => (n === 1 ? "1 pendiente" : `${n} pendientes`),
    paraManana: "Sugerencias para mañana",
    sinSugerencias: "Sin pendientes urgentes. ¡Buen cierre de día! 🎉",
  },
  actividades: {
    nueva: "Nueva actividad",
    editar: "Editar actividad",
    tipo: "Tipo",
    asunto: "Asunto",
    cuenta: "Empresa",
    oportunidad: "Oportunidad",
    contacto: "Contacto",
    fechaProgramada: "Fecha y hora",
    fechaVencimiento: "Vence",
    resultado: "Resultado",
    proximaAccion: "Próxima acción",
    notas: "Notas",
    estado: "Estado",
    completarTitulo: "Completar actividad",
    sinActividades: "Sin actividades",
    filtroTodas: "Todas",
  },
  reportes: {
    pestanaEquipo: "Equipo",
    pestanaMio: "Mi desempeño",
    pestanaSemanal: "Semanal",
    pestanaPipeline: "Dinero en juego",
    pestanaConversion: "Conversión",
    // Reporte semanal
    semanalTitulo: "Reporte semanal por ejecutivo",
    semanalNota: "Gestiones, proyectos trabajados, oportunidades avanzadas y adjudicaciones",
    semanaAnteriorBtn: "‹ Semana anterior",
    semanaSiguienteBtn: "Semana siguiente ›",
    colGestiones: "Gestiones",
    colPorTipo: "Detalle por tipo",
    colProyectosTrabajados: "Proyectos trabajados",
    colAvanzadas: "Oport. avanzadas",
    sinDatosSemana: "Sin gestión registrada en esa semana.",
    avanzadasNota: "Cambios de etapa registrados en la auditoría del sistema",
    // Reporte del dinero en juego (oportunidades abiertas)
    pipelineTitulo: "Dinero en juego",
    pipelineNota: "Valor por etapa, por ejecutivo y por rubro (solo oportunidades abiertas)",
    porEtapa: "Por etapa del embudo",
    porEjecutivo: "Por ejecutivo",
    porRubro: "Por rubro",
    oportunidadesN: (n: number) => (n === 1 ? "1 oportunidad" : `${n} oportunidades`),
    sinPipeline: "No hay oportunidades abiertas con esos filtros.",
    // Reporte de conversión
    conversionTitulo: "Conversión de proyectos del mercado",
    conversionDescripcion:
      "De los proyectos asignados: cuántos se contactaron, se convirtieron, enviaron propuesta y se adjudicaron",
    etapaAsignados: "Asignados",
    etapaContactados: "Contactados",
    etapaConvertidos: "Convertidos",
    etapaConPropuesta: "Con propuesta enviada",
    etapaAdjudicados: "Adjudicados",
    delPasoAnterior: (pct: number) => `${pct}% del paso anterior`,
    sinConversion: "Aún no hay proyectos asignados con esos filtros.",
    filtroRubro: "Rubro",
    filtroRegion: "Región",
    filtroDesde: "Asignados desde",
    todosMasc: "Todos",
    todasFem: "Todas",
    exportarPdfReporte: "Exportar PDF",
    abiertas: "Oportunidades abiertas",
    pipelineTotal: "Dinero en juego",
    actividadesHoyEquipo: "Actividades hoy",
    adjudicadasMes: "Adjudicadas este mes",
    ranking: "Ranking de ejecutivos",
    rankingNota: "Ordenado por gestión realizada en el mes",
    colEjecutivo: "Ejecutivo",
    colEquipo: "Equipo",
    colActividades: "Gestión (mes)",
    colHoy: "Hoy",
    colNuevas: "Nuevas",
    colAdjudicadas: "Adjudicadas",
    colAbiertas: "Abiertas",
    colMetas: "Metas",
    semaforo: { verde: "Cumpliendo", ambar: "En riesgo", rojo: "Bajo meta" },
    sinMetasFila: "sin metas",
    estancadas: "Oportunidades estancadas",
    estancadasNota: (dias: number) => `Más de ${dias} días sin actividad`,
    sinEstancadas: "Sin oportunidades estancadas. 🎉",
    diasSinActividad: (dias: number) => `${dias} días sin actividad`,
    embudoAgregado: "Embudo agregado",
    avanceMetas: "Avance vs meta del mes",
    sinMetas:
      "Sin metas definidas para este periodo. El administrador las configura en Administración → Metas.",
    kpis: "Mis números del mes",
    kpiActividades: "Actividades realizadas",
    kpiAdjudicadas: "Oportunidades adjudicadas",
    kpiNuevas: "Oportunidades nuevas",
    kpiConversion: "Tasa de conversión",
    conversionNota: "adjudicadas / cerradas del mes",
    comparativa: "Referencia del equipo",
    comparativaNota: "Promedio del equipo este mes — solo como referencia. 😉",
    tuValor: "Tú",
    promedioEquipo: "Promedio equipo",
    exportar: "Reportes exportables",
    reporteGestion: "⬇️ Gestión por ejecutivo (Excel)",
    reportePipeline: "⬇️ Dinero en juego por etapa y país (Excel)",
    imprimir: "🖨️ Versión imprimible / PDF",
    filtroPeriodo: "Periodo",
    filtroEjecutivo: "Ejecutivo",
    filtroPais: "País",
    generando: "Generando…",
    sinDatosExporte: "No hay datos para esos filtros",
    analisisEjecutivos: "Análisis de gestión por ejecutivo",
    analisisEjecutivosNota:
      "Cobertura de la cartera: contactos con gestión en los últimos 7 días, abandonados y mezcla de gestión (90 días)",
    conGestionReciente: "Con gestión (7 días)",
    sinGestionReciente: "Sin gestión reciente",
    contactosActivos: "contactos activos",
    masAbandonados: "Contactos con más días sin gestión",
    mezclaGestion: "Mezcla de gestión (90 días)",
    frecuenciaPromedio: (dias: number) => `Contacta a cada prospecto cada ~${dias} días`,
    sinFrecuencia: "Sin gestiones suficientes para calcular frecuencia",
    sinContactosActivos: "Sin prospectos ni empresas activas",
  },
  metasAdmin: {
    titulo: "Metas mensuales",
    descripcion:
      "Define la cuota de cada ejecutivo para el periodo. El avance se calcula solo, desde los datos reales.",
    objetivo: "Objetivo",
    sinComerciales: "No hay ejecutivos visibles",
    guardado: "Guardado ✓",
  },
  admin: {
    etapasEmbudo: "Etapas del embudo",
    etapasDescripcion:
      "Define las etapas del proceso comercial DIPREM. El orden controla el tablero de Oportunidades; la probabilidad se asigna automáticamente a las oportunidades que entran a la etapa.",
    nuevaEtapa: "Nueva etapa",
    nombreEtapa: "Nombre de la etapa",
    orden: "Orden",
    probabilidadDefault: "Probabilidad %",
    esGanada: "Etapa ganada (adjudicado)",
    esPerdida: "Etapa perdida",
    activa: "Activa",
    subir: "Subir",
    bajar: "Bajar",
  },
  fase0: {
    bienvenida: "Bienvenido/a",
    descripcionAdmin:
      "Usuarios, equipos y catálogo de servicios se configurarán aquí en una próxima etapa.",
  },
} as const;

export type Strings = typeof es;
