/**
 * Textos de UI centralizados (español). Único lugar donde viven los strings
 * visibles, compartido por web y móvil — preparado para i18n futuro (pt/en).
 */
export const es = {
  app: {
    nombre: "DIPREM CRM",
    lema: "Gestión comercial DIPREM",
  },
  auth: {
    titulo: "Iniciar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    entrar: "Entrar",
    entrando: "Entrando…",
    salir: "Cerrar sesión",
    errores: {
      emailRequerido: "Ingresa tu correo",
      emailInvalido: "Correo inválido",
      passwordCorta: "La contraseña debe tener al menos 6 caracteres",
      credenciales: "Correo o contraseña incorrectos",
      generico: "No se pudo iniciar sesión. Intenta de nuevo.",
    },
  },
  nav: {
    control: "Control",
    miDia: "Mi Día",
    cuentas: "Cuentas",
    oportunidades: "Oportunidades",
    actividades: "Actividades",
    propuestas: "Propuestas",
    mercado: "Mercado",
    reportes: "Reportes",
    admin: "Administración",
    perfil: "Perfil",
  },
  roles: {
    ejecutivo: "Ejecutivo Comercial",
    gerente: "Gerente Comercial",
    admin: "Administrador",
    lectura: "Solo lectura",
  },
  shell: {
    mas: "Más",
    menuCompleto: "Todo el menú",
    colapsar: "Colapsar menú",
    expandir: "Expandir menú",
    modoOscuro: "Modo oscuro",
    modoClaro: "Modo claro",
    accionesRapidas: "Acciones rápidas",
    accionGestion: "Registrar gestión",
    accionLead: "Nuevo lead",
    accionOportunidad: "Nueva oportunidad",
  },
  buscador: {
    placeholder: "Buscar cliente, lead, proyecto u oportunidad…",
    abrir: "Buscar",
    escribeParaBuscar: "Escribe al menos 2 letras para buscar en todo el CRM",
    sinResultados: (texto: string) => `Sin resultados para "${texto}"`,
    grupos: {
      cuenta: "Cuentas",
      lead: "Leads",
      oportunidad: "Oportunidades",
      proyecto: "Proyectos del mercado",
      ejecutivo: "Ejecutivos",
    },
  },
  comunes: {
    cargando: "Cargando…",
    reintentar: "Reintentar",
    proximamente: "Disponible en una próxima fase",
    sinAcceso: "No tienes acceso a esta sección",
    guardar: "Guardar",
    guardando: "Guardando…",
    cancelar: "Cancelar",
    crear: "Crear",
    editar: "Editar",
    eliminar: "Eliminar",
    buscar: "Buscar…",
    sinResultados: "Sin resultados",
    errorGenerico: "Ocurrió un error. Intenta de nuevo.",
    confirmarEliminar: "¿Seguro que quieres eliminar este registro?",
    opcional: "opcional",
    todos: "Todos",
  },
  crm: {
    nuevaCuenta: "Nueva cuenta",
    editarCuenta: "Editar cuenta",
    razonSocial: "Razón social",
    taxId: "RUT / CUIT / Tax ID",
    vertical: "Vertical",
    pais: "País",
    ciudad: "Ciudad",
    sitioWeb: "Sitio web",
    estado: "Estado",
    propietario: "Ejecutivo",
    sinCuentas: "Aún no tienes cuentas. Crea la primera o convierte un lead.",
    contactos: "Contactos",
    nuevoContacto: "Nuevo contacto",
    editarContacto: "Editar contacto",
    nombre: "Nombre",
    cargo: "Cargo",
    telefono: "Teléfono",
    correo: "Correo",
    canalPreferido: "Canal preferido",
    contactoPrincipal: "Contacto principal",
    sinContactos: "Sin contactos registrados",
    linkedin: "LinkedIn",
    mejorHorario: "Mejor horario para contactar",
    mejorHorarioPlaceholder: "Ej: martes a jueves, 9:00–11:00",
    notasPrivadas: "Notas privadas",
    notasPrivadasAyuda: "Internas DIPREM: no salen en la ficha PDF.",
    fichaContacto: "Ficha de contacto",
    verFicha: "Ver ficha",
    exportarPdf: "Ficha en PDF",
    historialContacto: "Historial con este contacto",
    historialContactoNota:
      "Todas las interacciones con esta persona, sin importar el proyecto u oportunidad",
    leads: "Leads",
    nuevoLead: "Nuevo lead",
    editarLead: "Editar lead",
    empresa: "Empresa",
    fuente: "Fuente",
    calificacion: "Calificación",
    notas: "Notas",
    convertir: "Convertir",
    convertirLead: "Convertir lead en cuenta + oportunidad",
    convertido: "Convertido",
    descartarLead: "Descartar",
    sinLeads: "Sin leads por gestionar",
    oportunidades: "Oportunidades",
    nuevaOportunidad: "Nueva oportunidad",
    editarOportunidad: "Editar oportunidad",
    nombreOportunidad: "Nombre de la oportunidad",
    cuenta: "Cuenta",
    monto: "Monto",
    moneda: "Moneda",
    modalidad: "Modalidad de contrato",
    pilar: "Pilar",
    lineaServicio: "Línea de servicio",
    servicio: "Servicio",
    fechaCierre: "Cierre estimado",
    probabilidad: "Probabilidad",
    etapa: "Etapa",
    moverA: "Mover a…",
    motivoPerdida: "Motivo de pérdida",
    detalleMotivoPerdida: "Detalle (opcional)",
    registrarPerdida: "Registrar pérdida",
    sinOportunidades: "Sin oportunidades en esta etapa",
    totalPipeline: "Total",
    adjudicada: "Adjudicada 🎉",
    embudo: "Embudo de ventas",
  },
  control: {
    titulo: "Panel de Control",
    descripcion:
      "Visión en tiempo real de la operación comercial: qué se asignó, quién lo está trabajando y dónde intervenir.",
    metricaProyectos: "Proyectos asignados",
    metricaProyectosNota: (trabajados: number) =>
      `${trabajados} trabajados esta semana`,
    metricaMejor: "Mejor gestión del mes",
    metricaMejorNota: (gestiones: number) =>
      gestiones === 1 ? "1 gestión registrada" : `${gestiones} gestiones registradas`,
    sinGestionesMes: "Sin gestiones aún este mes",
    metricaRiesgo: "Oportunidades en riesgo",
    metricaRiesgoNota: (dias: number) => `Más de ${dias} días sin actividad`,
    metricaPipeline: "Pipeline abierto",
    metricaPipelineNota: "Suma de oportunidades abiertas",
    semaforoTitulo: "Semáforo de ejecutivos",
    semaforoNota: "Actividad de los últimos 7 días y cumplimiento de metas del mes",
    colGestion7d: "Gestión (7 días)",
    colCumplimiento: "Cumplimiento",
    sinGestionTitulo: "Proyectos sin gestión",
    sinGestionNota: (dias: number) =>
      `Asignados sin ninguna actividad en los últimos ${dias} días`,
    todosGestionados: "Todos los proyectos asignados tienen gestión reciente. 🎉",
    recordar: "Recordar",
    recordando: "Enviando…",
    recordatorioEnviado: "Recordatorio enviado ✓",
    vencido: "Vencido",
    fechaLimiteCorta: "Límite",
    notaDelDueno: "Nota de quien asignó",
    historialTitulo: "Historial de asignaciones",
    historialNota: "Quién asignó qué proyecto, a quién y cuándo",
    colProyecto: "Proyecto",
    colAsignadoA: "Asignado a",
    colAsignadoPor: "Asignado por",
    colFecha: "Fecha",
    colEstado: "Estado",
    sinAsignaciones: "Aún no hay proyectos asignados.",
    verLead: "Ver lead",
  },
  notificaciones: {
    titulo: "Recordatorios",
    marcarLeida: "Marcar como vista",
    sinPendientes: "Sin recordatorios pendientes",
  },
  mercado: {
    titulo: "Mercado nacional",
    descripcion:
      "Base de proyectos del mercado. Importa desde Excel/CSV y asigna proyectos a tus ejecutivos como leads.",
    importar: "Importar proyectos",
    importarTitulo: "Importar proyectos del mercado",
    seleccionarArchivo: "Selecciona un archivo Excel (.xlsx) o CSV",
    formatoAyuda:
      "Columnas esperadas: nombre del proyecto, empresa, rubro, región, monto estimado, contacto, teléfono, correo, fuente. La primera fila debe traer los encabezados.",
    analizando: "Analizando archivo…",
    previewTitulo: "Revisión antes de importar",
    filasValidas: (n: number) => (n === 1 ? "1 proyecto listo para cargar" : `${n} proyectos listos para cargar`),
    filasConError: (n: number) => (n === 1 ? "1 fila con errores (no se importará)" : `${n} filas con errores (no se importarán)`),
    duplicadosArchivo: (n: number) => `${n} duplicados dentro del archivo (se cargan una sola vez)`,
    confirmarImportar: "Importar",
    importando: "Importando…",
    resultadoImportacion: (insertados: number, duplicados: number) =>
      `Se importaron ${insertados} proyectos. ${duplicados > 0 ? `${duplicados} ya existían y no se duplicaron.` : ""}`,
    sinProyectos: "Aún no hay proyectos importados. Sube tu primer archivo del mercado.",
    proyecto: "Proyecto",
    empresa: "Empresa",
    rubro: "Rubro",
    region: "Región",
    montoEstimado: "Monto estimado",
    contacto: "Contacto",
    fuente: "Fuente",
    estado: "Estado",
    asignadoA: "Asignado a",
    estados: {
      sin_asignar: "Sin asignar",
      asignado: "Asignado",
      convertido: "Convertido",
    },
    asignar: "Asignar",
    asignarSeleccionados: (n: number) => (n === 1 ? "Asignar 1 proyecto" : `Asignar ${n} proyectos`),
    asignarTitulo: "Asignar proyectos a un ejecutivo",
    asignarDescripcion:
      "Cada proyecto se convierte en un lead nuevo del ejecutivo, con el teléfono y correo del contacto ya cargados. Lo verá destacado en su Mi Día.",
    ejecutivo: "Ejecutivo",
    prioridad: "Prioridad",
    fechaLimite: "Fecha límite de primer contacto",
    notaPrivada: "Nota para el ejecutivo",
    notaPrivadaAyuda:
      "Privada: solo la ven el ejecutivo asignado, su gerente y el administrador.",
    notaPlaceholder: "Ej: Este contacto conoce a Pedro, di que vas de parte de él",
    diasAlerta: "Alertarme si no hay gestión en (días)",
    asignando: "Asignando…",
    resultadoAsignacion: (asignados: number, omitidos: number) =>
      `${asignados} ${asignados === 1 ? "proyecto asignado" : "proyectos asignados"}.${omitidos > 0 ? ` ${omitidos} ya estaban asignados y se omitieron.` : ""}`,
    seleccionados: (n: number) => `${n} seleccionados`,
  },
  gestion: {
    titulo: "Análisis de gestión",
    ultimaGestion: "Última gestión",
    diasSinGestion: (dias: number) =>
      dias === 0 ? "gestionado hoy" : dias === 1 ? "1 día sin gestión" : `${dias} días sin gestión`,
    sinGestiones: "Aún no hay gestiones registradas para este contacto.",
    resumenTipos: "Gestiones realizadas",
    proximaAccion: "Próxima acción",
    sinProximaAccion: "Sin próxima acción definida — agenda la siguiente gestión.",
    intensidad: "Intensidad de gestión",
    lineaTiempo: "Historial de gestiones",
    verMas: "Ver más",
    llamar: "Llamar",
    whatsapp: "WhatsApp",
    escribirCorreo: "Escribir correo",
  },
  miDia: {
    agendaHoy: "Agenda de hoy",
    vencidas: "Vencidas",
    sinAgenda: "Nada agendado para hoy. Usa el registro rápido para sumar gestión.",
    seguimientos: "Seguimientos pendientes",
    sinSeguimientos: "Sin oportunidades abiertas que requieran seguimiento. 👌",
    diasSinContacto: (dias: number) =>
      dias === 0 ? "contactada hoy" : dias === 1 ? "1 día sin contacto" : `${dias} días sin contacto`,
    registrarGestion: "Registrar gestión",
    registroRapido: "Registro rápido",
    resumenDia: "Resumen del día",
    completadasHoy: "completadas hoy",
    pendientesHoy: "pendientes",
    alertasSeguimiento: "con alerta",
    completar: "Completar",
    completada: "Hecha ✓",
    yaRealizada: "Ya realizada (registrar como hecha)",
    hoy: "Hoy",
    manana: "Mañana",
    leadsNuevos: "Leads nuevos asignados",
    leadsNuevosNota: "Proyectos del mercado y leads que esperan tu primer contacto",
    verLead: "Ver lead",
    prioritarios: "Proyectos prioritarios de hoy",
    prioritariosNota: "Por dónde empezar: prioridad del dueño, fecha límite y urgencia",
    racha: (dias: number) =>
      dias === 1 ? "1 día seguido con gestión" : `${dias} días seguidos con gestión`,
    sinRacha: "Registra una gestión hoy para partir tu racha",
    gestionesSemana: "Gestión de la semana",
    gestionesSemanaDe: (hechas: number, meta: number) => `${hechas} de ${meta}`,
    gestionesSemanaSinMeta: (hechas: number) =>
      hechas === 1 ? "1 gestión esta semana" : `${hechas} gestiones esta semana`,
    metaSemanalNota: "Meta semanal derivada de tu meta mensual de actividades",
    resumenFinDia: "Resumen del día",
    resumenFinDiaNota: "Lo que se hizo hoy y por dónde partir mañana",
    hicisteHoy: (n: number) => (n === 1 ? "Registraste 1 gestión hoy" : `Registraste ${n} gestiones hoy`),
    quedaronPendientes: (n: number) => (n === 1 ? "1 pendiente" : `${n} pendientes`),
    paraManana: "Sugerencias para mañana",
    sinSugerencias: "Sin pendientes urgentes. ¡Buen cierre de día! 🎉",
  },
  actividades: {
    nueva: "Nueva actividad",
    editar: "Editar actividad",
    tipo: "Tipo",
    asunto: "Asunto",
    cuenta: "Cuenta",
    oportunidad: "Oportunidad",
    contacto: "Contacto",
    fechaProgramada: "Fecha y hora",
    fechaVencimiento: "Vence",
    resultado: "Resultado",
    proximaAccion: "Próxima acción",
    notas: "Notas",
    estado: "Estado",
    completarTitulo: "Completar actividad",
    sinActividades: "Sin actividades",
    filtroTodas: "Todas",
  },
  reportes: {
    pestanaEquipo: "Equipo",
    pestanaMio: "Mi desempeño",
    pestanaSemanal: "Semanal",
    pestanaPipeline: "Pipeline",
    pestanaConversion: "Conversión",
    // Reporte semanal
    semanalTitulo: "Reporte semanal por ejecutivo",
    semanalNota: "Gestiones, proyectos trabajados, oportunidades avanzadas y adjudicaciones",
    semanaAnteriorBtn: "‹ Semana anterior",
    semanaSiguienteBtn: "Semana siguiente ›",
    colGestiones: "Gestiones",
    colPorTipo: "Detalle por tipo",
    colProyectosTrabajados: "Proyectos trabajados",
    colAvanzadas: "Oport. avanzadas",
    sinDatosSemana: "Sin gestión registrada en esa semana.",
    avanzadasNota: "Cambios de etapa registrados en la auditoría del sistema",
    // Reporte de pipeline
    pipelineTitulo: "Pipeline abierto",
    pipelineNota: "Valor por etapa, por ejecutivo y por rubro (solo oportunidades abiertas)",
    porEtapa: "Por etapa del embudo",
    porEjecutivo: "Por ejecutivo",
    porRubro: "Por rubro",
    oportunidadesN: (n: number) => (n === 1 ? "1 oportunidad" : `${n} oportunidades`),
    sinPipeline: "No hay oportunidades abiertas con esos filtros.",
    // Reporte de conversión
    conversionTitulo: "Conversión de proyectos del mercado",
    conversionDescripcion:
      "De los proyectos asignados: cuántos se contactaron, se convirtieron, enviaron propuesta y se adjudicaron",
    etapaAsignados: "Asignados",
    etapaContactados: "Contactados",
    etapaConvertidos: "Convertidos",
    etapaConPropuesta: "Con propuesta enviada",
    etapaAdjudicados: "Adjudicados",
    delPasoAnterior: (pct: number) => `${pct}% del paso anterior`,
    sinConversion: "Aún no hay proyectos asignados con esos filtros.",
    filtroRubro: "Rubro",
    filtroRegion: "Región",
    filtroDesde: "Asignados desde",
    todosMasc: "Todos",
    todasFem: "Todas",
    exportarPdfReporte: "Exportar PDF",
    abiertas: "Oportunidades abiertas",
    pipelineTotal: "Pipeline total",
    actividadesHoyEquipo: "Actividades hoy",
    adjudicadasMes: "Adjudicadas este mes",
    ranking: "Ranking de ejecutivos",
    rankingNota: "Ordenado por gestión realizada en el mes",
    colEjecutivo: "Ejecutivo",
    colEquipo: "Equipo",
    colActividades: "Gestión (mes)",
    colHoy: "Hoy",
    colNuevas: "Nuevas",
    colAdjudicadas: "Adjudicadas",
    colAbiertas: "Abiertas",
    colMetas: "Metas",
    semaforo: { verde: "Cumpliendo", ambar: "En riesgo", rojo: "Bajo meta" },
    sinMetasFila: "sin metas",
    estancadas: "Oportunidades estancadas",
    estancadasNota: (dias: number) => `Más de ${dias} días sin actividad`,
    sinEstancadas: "Sin oportunidades estancadas. 🎉",
    diasSinActividad: (dias: number) => `${dias} días sin actividad`,
    embudoAgregado: "Embudo agregado",
    avanceMetas: "Avance vs meta del mes",
    sinMetas:
      "Sin metas definidas para este periodo. El administrador las configura en Administración → Metas.",
    kpis: "Mis KPIs del mes",
    kpiActividades: "Actividades realizadas",
    kpiAdjudicadas: "Oportunidades adjudicadas",
    kpiNuevas: "Oportunidades nuevas",
    kpiConversion: "Tasa de conversión",
    conversionNota: "adjudicadas / cerradas del mes",
    comparativa: "Referencia del equipo",
    comparativaNota: "Promedio del equipo este mes — solo como referencia. 😉",
    tuValor: "Tú",
    promedioEquipo: "Promedio equipo",
    exportar: "Reportes exportables",
    reporteGestion: "⬇️ Gestión por ejecutivo (Excel)",
    reportePipeline: "⬇️ Pipeline por etapa y país (Excel)",
    imprimir: "🖨️ Versión imprimible / PDF",
    filtroPeriodo: "Periodo",
    filtroEjecutivo: "Ejecutivo",
    filtroPais: "País",
    generando: "Generando…",
    sinDatosExporte: "No hay datos para esos filtros",
    analisisEjecutivos: "Análisis de gestión por ejecutivo",
    analisisEjecutivosNota:
      "Cobertura de la cartera: contactos con gestión en los últimos 7 días, abandonados y mezcla de gestión (90 días)",
    conGestionReciente: "Con gestión (7 días)",
    sinGestionReciente: "Sin gestión reciente",
    contactosActivos: "contactos activos",
    masAbandonados: "Contactos con más días sin gestión",
    mezclaGestion: "Mezcla de gestión (90 días)",
    frecuenciaPromedio: (dias: number) => `Contacta a cada prospecto cada ~${dias} días`,
    sinFrecuencia: "Sin gestiones suficientes para calcular frecuencia",
    sinContactosActivos: "Sin leads ni cuentas activas",
  },
  metasAdmin: {
    titulo: "Metas mensuales",
    descripcion:
      "Define la cuota de cada ejecutivo para el periodo. El avance se calcula solo, desde los datos reales.",
    objetivo: "Objetivo",
    sinComerciales: "No hay ejecutivos visibles",
    guardado: "Guardado ✓",
  },
  admin: {
    etapasEmbudo: "Etapas del embudo",
    etapasDescripcion:
      "Define las etapas del proceso comercial DIPREM. El orden controla el Kanban; la probabilidad se asigna automáticamente a las oportunidades que entran a la etapa.",
    nuevaEtapa: "Nueva etapa",
    nombreEtapa: "Nombre de la etapa",
    orden: "Orden",
    probabilidadDefault: "Probabilidad %",
    esGanada: "Etapa ganada (adjudicado)",
    esPerdida: "Etapa perdida",
    activa: "Activa",
    subir: "Subir",
    bajar: "Bajar",
  },
  fase0: {
    bienvenida: "Bienvenido/a",
    descripcionMiDia:
      "Aquí verás tu agenda del día, seguimientos pendientes y avance de metas (Fase 2).",
    descripcionCuentas: "Gestión de cuentas y contactos (Fase 1).",
    descripcionOportunidades: "Embudo de ventas DIPREM en Kanban (Fase 1).",
    descripcionActividades: "Registro de llamadas, reuniones y visitas a terreno (Fase 2).",
    descripcionPropuestas: "Propuestas con versiones y aprobación gerencial (Fase 4).",
    descripcionReportes: "KPIs y reportes exportables (Fase 3).",
    descripcionAdmin: "Embudo, servicios, usuarios, equipos y metas (por fases).",
  },
} as const;

export type Strings = typeof es;
